version: 2.1
executors:
  default:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:latest
commands:
  yarn_restore:
    steps:
      - restore_cache:
          keys:
            - >-
              yarn-packages-{{
              checksum "yarn.lock"
              }}-{{
              checksum "src/.vuepress/plugins/my-blog/yarn.lock"
              }}
  yarn_save:
    steps:
      - save_cache:
          name: Save yarn package Cache.
          key: >-
              yarn-packages-{{
              checksum "yarn.lock"
              }}-{{
              checksum "src/.vuepress/plugins/my-blog/yarn.lock"
              }}
          paths:
            - ~/.cache/yarn
jobs:
  build:
    executor: default
    steps:
      - checkout
      - yarn_restore
      - run:
          name: Install dependencies.
          command: |
            yarn --frozen-lockfile
      - yarn_save
      - run:
          name: Generate pages.
          command: |
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public
            - now.json
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies for deployment.
          command: |
            yarn config set prefix ~/.yarn
            yarn global add now
      - run:
          name: Deploy to Now.
          command: |
            ~/.yarn/bin/now --token=$NOW_TOKEN
            ~/.yarn/bin/now --token=$NOW_TOKEN alias

workflows:
  publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
