version: 2.1
executors:
  default:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:latest
commands:
  yarn_restore:
    steps:
      - restore_cache:
          name: Restore yarn package cache.
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
  yarn_save:
    steps:
      - save_cache:
          name: Save yarn package Cache.
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  build:
    executor: default
    steps:
      - checkout
      - yarn_restore
      - run:
          name: Install dependencies.
          command: yarn --frozen-lockfile
      - yarn_save
      - run:
          name: Generate pages.
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies for deployment.
          command: |
            yarn config set prefix ~/.yarn
            yarn global add firebase-tools
      - run:
          name: Deploy to Firebase Hosting.
          command: ~/.yarn/bin/firebase deploy
                   --project $FIREBASE_PROJECT_ID --token=$FIREBASE_ACCESS_TOKEN
workflows:
  publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
