version: 2.1
orbs:
  node: circleci/node@1.1.2
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Fetch submodules
          command: |
            git submodule update --init
      - node/with-cache:
          dir: ./node_modules
          cache-key: ./yarn.lock
          steps:
            - run:
                name: Install core
                command: |
                  yarn --frozen-lockfile
      - node/with-cache:
          dir: ./src/.vuepress/plugins/blog/node_modules
          cache-key: ./src/.vuepress/plugins/blog/package.json
          steps:
            - run:
                name: Install local plugin
                command: |
                  yarn install:plugin && yarn build:plugin
      - run:
          name: Generate pages.
          command: |
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public
            - now.json
  deploy:
    executor:
      name: node/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies for deployment.
          command: |
            yarn global add now
      - run:
          name: Deploy to Now.
          command: |
            $(yarn global bin)/now --token=$NOW_TOKEN --target production 
workflows:
  publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
